# Generated by Django 5.0 on 2024-01-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbapp', '0008_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
